version: '3.9'

services:
  db:
    image: postgres:15.1-alpine3.17
    container_name: yotemi_db
    restart: always
    tty: true
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'yotemi'
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    secrets:
      - postgres_password

  redis:
    image: redis:7.0.7-alpine3.17
    container_name: yotemi_redis
    restart: unless-stopped
    tty: true
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  data:
    name: yotemi_data
    external: true
  redis_data:
    name: yotemi_redis_data
    external: true

secrets:
  postgres_password:
    file: ./docker_postgres_password